[Eth]
NetworkId = 1
SyncMode = "fast"
NoPruning = false
LightPeers = 100
DatabaseCache = 512
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000 
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

[Eth.TxPool]
Locals = []
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 512
GlobalSlots = 10000
AccountQueue = 256
GlobalQueue = 5000
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60 

[Node]
IPCPath = "geth.ipc"
HTTPPort = 29900
HTTPHost = "0.0.0.0"
HTTPCors = ["*"]
HTTPVirtualHosts = ["*"]
HTTPModules = ["net", "web3", "eth","admin","txpool"]
#WSPort = 29901
#WSModules = ["net", "web3", "eth","admin","txpool"]

[Node.P2P]
MaxPeers = 25
NoDiscovery = false
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

